site_name: Gluu Docs
site_description: Documenation for Gluu Cluster Manager
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2017, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-clustermgr-prod
theme_dir: theme/material
extra:
    version: '3.0.1'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Installation Guide:
        - 'Install Cluster Manager': 'installation/installation.md'
- Upgrade/Patch Guide:
        - 'Upgrade Gluu Cluster Manager' : 'installation/upgrade.md'
- Configuration Guide:
        - 'Configuring Gluu CE for Replication' : 'configuration/configuring-GluuCE-Cluster.md'
        - 'Configuring oxAuth logs': 'configuration/configuring-oxAuth-Logs.md'
        - 'Configuring oxAuth Key Rotation' : 'configuration/configuring-oxAuth-Key-Rotation.md'
- Replication Guide:
        - 'Replication': 'replication/Setting-up-LDAP-replication.md'
- Troubleshooting:
        - 'Troubleshooting Issues': 'troubleshooting/troubleshooting.md'