# Project information
site_name: Cluster Manager Docs
site_description: Documentation for Gluu Cluster Manager
site_favicon: 'favicon.ico'

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: source
#repo_name: GluuFederation/docs-ce-prod
repo_url: https://github.com/GluuFederation/docs-clustermgr-prod/tree/3.1.4/3.1.4
#repo_url: https://github.com/GluuFederation/docs-clustermgr-prod/
#edit_uri: edit/3.1.4/3.1.4/source

# Configuration
theme_dir: theme/material
#theme: 
#    name: material
#    palette:
#        primary: 'green'
#        accent: 'green'
#    logo: 'gluu.jpg'
#    favicon: 'favicon.ico'
extra:
    version: '3.1.4'
    logo: 'gluu.png'
    
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
#- codehilite     
- pymdownx.superfences

# Navigation
#nav:
#- 'Versions':
#    - '3.1.4': 'https://gluu.org/docs/cm/3.1.4/'
#    - '3.1.3': 'https://gluu.org/docs/ce/3.1.3/'
#    - 'beta': 'https://gluu.org/docs/ce/beta/'
#- ' ': 'https:/gluu.org/docs'
#- ' ': 'https:/gluu.org/docs'
pages:
- Home: 'index.md'
- Install: 'installation/index.md'
- Deploy Clusters: 'deploy/index.md'
- Configure SSO (optional): 'authentication/index.md'
- Configure AWS Load Balancer: 'aws-config/index.md'
- Troubleshooting: 'troubleshooting/index.md'
