# Project information
site_name: Cluster Manager 3.1.6 Docs
site_description: Documentation for Gluu Cluster Manager

# Copyright
copyright: Copyright &copy; 2019, Gluu, Inc.

# Repository
docs_dir: source
repo_name: GluuFederation/docs-clustermgr-prod
repo_url: https://github.com/GluuFederation/docs-clustermgr-prod/
edit_uri: edit/3.1.6/docs/source

# Configuration
theme: 
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '3.1.6'

# Tracking
google_analytics:
  - 'UA-31008645-7'
  - 'auto'
  
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite     
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '3.1.6': 'https://gluu.org/docs/cm/3.1.6/'
    - '4.1': 'https://gluu.org/docs/cm/4.1/'
    - '4.0': 'https://gluu.org/docs/cm/4.0/'
    - '3.1.4': 'https://gluu.org/docs/cm/3.1.4/'
    - '3.1.3': 'https://gluu.org/docs/cm/3.1.3/'
    - 'beta': 'https://gluu.org/docs/cm/beta/'
- ' ': 'https:/gluu.org/docs'
- ' ': 'https:/gluu.org/docs'
- Home: 'index.md'
- Install: 'installation/index.md'
- Deploy Clusters: 'deploy/index.md'
- Configure AWS Load Balancer: 'aws-config/index.md'
- Troubleshooting: 'troubleshooting/index.md'
