site_name: Cluster Manager Docs
site_description: Documentation for Gluu Cluster Manager
site_favicon: 'favicon.ico'
copyright: Copyright &copy; 2019, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs-clustermgr-prod/tree/4.0/docs
theme_dir: theme/material
extra:
    version: '4.0'
    logo: 'gluu.png'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Install: 'installation/index.md'
- Deploy Clusters: 'deploy/index.md'
- Configure AWS Load Balancer: 'aws-config/index.md'
- Troubleshooting: 'troubleshooting/index.md'
